### ISSUE TITLE
How to get complete dataset

### ISSUE THREAD

**Issue by debug-zhang** [elastisys/MicroRCA#3]
Thank you for sharing.

But how could we get the complete dataset, which is important to follow your work?

**Comment by debug-zhang** [comment]
Run `python MicroRCA.py`

Output:

target: carts  fault_type: service_cpu
./data/service_cpu_carts
1
2
Traceback (most recent call last):
  File "MicroRCA.py", line 321, in <module>
    anomaly_score = anomaly_subgraph(DG, anomalies, latency_df, faults_name, alpha)
  File "MicroRCA.py", line 217, in anomaly_subgraph
    data, col = node_weight(u, anomaly_graph, baseline_df, faults_name)
  File "MicroRCA.py", line 112, in node_weight
    df = pd.read_csv(filename)
……
FileNotFoundError: [Errno 2] No such file or directory: './data/service_cpu_carts_shipping.csv'

**Comment by LillyWu** [comment]
@storagezhang  Thanks for your interest in our work.  To validate the results, I recommend that you set up a Kubernetes and istio testbed as described in our paper. The code available in the github repo contains the algorithms, and some example .csv files to illustrate the data format. The full data files from the paper are not publicly available.

**Comment by debug-zhang** [comment]
@LillyWu Thanks for your reply.
