### ISSUE TITLE
some questions about dataset

### ISSUE THREAD

**Issue by Yongli0510** [elastisys/MicroRCA#4]
Thanks for your work！I have some questions about the sample dataset. 

1. What is the difference between metrics "ctn_xxx" and "node_xxx"(xxx is one of cpu/mem/network)? Do they represent two different forms of cpu/mem/network? 
2. I have noticed that you used the two different types of cpu/memory/network metrics above when calculating weight and PPV of the same node.Why is it designed this way?

Thank you for your answers in advance .

**Comment by LillyWu** [comment]
@Yongli0510 Thank you for your effort in approaching me via email. I hope my reply helped.
